In [ ]:
import numpy as np

##1.random

In [ ]:
np.random.random(50)
#giving value between 0 and 1

array([0.04719464, 0.37144428, 0.17727294, 0.22913423, 0.71431326,
       0.79486007, 0.13931124, 0.81618748, 0.85770174, 0.09347013,
       0.19143793, 0.66826804, 0.56004798, 0.64697698, 0.66905378,
       0.69362438, 0.81556718, 0.98347817, 0.13483297, 0.91758604,
       0.45731599, 0.88399891, 0.99765819, 0.66925432, 0.46649501,
       0.52167961, 0.81097828, 0.46658363, 0.86695476, 0.999029  ,
       0.20454291, 0.96328812, 0.95692197, 0.25590044, 0.76661986,
       0.78639499, 0.85830046, 0.86787635, 0.64385455, 0.93414682,
       0.8922758 , 0.81242158, 0.86109454, 0.20770259, 0.84101062,
       0.59128685, 0.43328975, 0.75705786, 0.83520306, 0.46030821])

In [ ]:
np.random.seed(775)
np.random.random()
#it gives every time same value only if we provide some input value of seed

0.37573502088758925

In [ ]:
a=np.random.randint(20,88,40).reshape(8,5)
a

array([[70, 79, 49, 21, 27],
       [44, 40, 31, 76, 71],
       [47, 75, 54, 65, 26],
       [49, 83, 70, 21, 28],
       [27, 29, 37, 52, 39],
       [20, 37, 47, 21, 27],
       [45, 84, 71, 71, 53],
       [40, 69, 24, 49, 54]])

In [ ]:
np.random.uniform(3,88,40).reshape(8,5)
# It gives float numbers

array([[21.19389656, 32.26398648,  5.09846372, 34.90203431, 23.52747853],
       [82.63514881, 70.56831697, 47.59336674,  7.73077487, 31.06249894],
       [31.34307187, 68.61449327, 80.61420171,  3.41890012, 20.99612043],
       [59.18834822, 75.47347388, 42.41381949, 83.01565469, 65.02348596],
       [57.64657447, 40.27165336,  4.94168985, 44.74800983, 64.38651434],
       [86.16765962,  8.71323583, 23.37417914, 34.14344881, 14.82473824],
       [56.33967209, 38.19158098, 51.05774968, 58.75122625, 36.56921845],
       [43.83809925, 35.04929415, 37.70904741, 87.96965504,  9.0020354 ]])

In [ ]:
np.random.randint(19,20,20).reshape(4,5)

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

##2.max/min

##3.argmax/argmin

**It gives the index of highest and lowest element present**

In [ ]:
a

array([[20, 35, 79, 39, 87],
       [86, 26, 51, 32, 45],
       [81, 24, 48, 23, 36],
       [27, 74, 44, 48, 81],
       [40, 86, 59, 41, 25],
       [79, 22, 78, 78, 42],
       [78, 67, 44, 37, 44],
       [65, 39, 51, 75, 81]])

In [ ]:
a.max()

87

In [ ]:
np.argmax(a)

4

In [ ]:
np.argmin(a)

0

In [ ]:
np.argmin(a,axis=0)

array([0, 5, 3, 2, 4])

##4.conditional indexing(already done in filtering)

In [ ]:
a[(a%2==1)&(a>50)]=0
a
#every number greater than 50 and odd are converted to zero

array([[20, 35,  0, 39,  0],
       [86, 26,  0, 32, 45],
       [ 0, 24, 48, 23, 36],
       [27, 74, 44, 48,  0],
       [40, 86,  0, 41, 25],
       [ 0, 22, 78, 78, 42],
       [78,  0, 44, 37, 44],
       [ 0, 39,  0,  0,  0]])

##5.where
this function is used when we donot want to change the array itself but just want to change the values.

**syntax=[condition,   what if true,  what if false]**

In [ ]:
a1=np.where(a%2==1,0,a)
a1

array([[20,  0,  0,  0,  0],
       [86, 26,  0, 32,  0],
       [ 0, 24, 48,  0, 36],
       [ 0, 74, 44, 48,  0],
       [40, 86,  0,  0,  0],
       [ 0, 22, 78, 78, 42],
       [78,  0, 44,  0, 44],
       [ 0,  0,  0,  0,  0]])

In [ ]:
a1
# It remains unchanged(permanent change is induced)?

array([[20,  0,  0,  0,  0],
       [86, 26,  0, 32,  0],
       [ 0, 24, 48,  0, 36],
       [ 0, 74, 44, 48,  0],
       [40, 86,  0,  0,  0],
       [ 0, 22, 78, 78, 42],
       [78,  0, 44,  0, 44],
       [ 0,  0,  0,  0,  0]])

##6.sort

In [ ]:
a

array([[70, 79, 49, 21, 27],
       [44, 40, 31, 76, 71],
       [47, 75, 54, 65, 26],
       [49, 83, 70, 21, 28],
       [27, 29, 37, 52, 39],
       [20, 37, 47, 21, 27],
       [45, 84, 71, 71, 53],
       [40, 69, 24, 49, 54]])

In [ ]:
np.sort(a,axis=0)

array([[20, 29, 24, 21, 26],
       [27, 37, 31, 21, 27],
       [40, 40, 37, 21, 27],
       [44, 69, 47, 49, 28],
       [45, 75, 49, 52, 39],
       [47, 79, 54, 65, 53],
       [49, 83, 70, 71, 54],
       [70, 84, 71, 76, 71]])

##7.percentile

A percentile is a comparison score between a particular score and the scores of the rest of a group. It shows the percentage of scores that a particular score surpassed. For example, if you score 75 points on a test, and are ranked in the 85th percentile, it means that the score 75 ishigher than 85% of the scores.

In [ ]:
np.percentile(a,0)

20.0

In [ ]:
np.percentile(a,50)

47.0

In [ ]:
np.percentile(a,100)
#highest value in data

84.0

In [ ]:
np.percentile(a,0)
#lowest value in data

20.0