- **NUMERICAL PYTHON** is a library written in C and FORTRAN especially for high level mathematical function.
- python is user friendly programming language because of its simple syntax and very useful in application building,and it was possible beacuse developers done work on its inner code(we donot care about memory location as in c).
- **C=>** used when needs to be communicated with hardware(has great layer of abstraction)
- **python =>** when application need to be build(user-centric)
- But the problem with python is that no doubt their data structures are numerous and powerful but extremely slow when needs to deal with large data.
- The solution is Numpy
- **c (speed) + python (syntax feasibility)**.....>>>best for machine learning
(initialy not possible when python was developed)

# APPLICATION
- ONE data type = N-dimensional arrays
- sophistecated functions
- perform high level methamatical operations

# properties of n-d arrays
- homogeneous(same data type stored) like int,float,complex\
- fixed item size
- Actually it can hold strings but we dont use numpy in that way.



---



---



---



#Create n-d Arrays

In [ ]:
import numpy as np

**1.np.array**

In [ ]:
array=np.array([1,2,3])
type(array)

numpy.ndarray

In [ ]:
array1=np.array([1,2,34,5,5.5,"string"])
print(array1)
# 1D array

['1' '2' '34' '5' '5.5' 'string']


In [ ]:
type(array1)

numpy.ndarray

In [ ]:
python_list=[[1,2],[3,4]]
python_list

[[1, 2], [3, 4]]

In [ ]:
array2=np.array([[1,2],[3,4]])
print(array2)
# 2D arrays
#output looks like a matrices

[[1 2]
 [3 4]]


**2.np.zeros/ones/empty/random**(values are returned as floats)

In [ ]:
array3=np.zeros((4,5),dtype=int)
array3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
array3=np.zeros((2,3),dtype=int)
array3

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
array4=np.ones([2,3])
array4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
array5=np.empty([3,3],dtype=int)
array5

array([[98664134259745,              0,              0],
       [             0,              0,              0],
       [             0,              0,              0]])

In [ ]:
array6=np.random.randint(1,1000)
array6

846

**3.np.identity**

A square matrix in which all the elements of the principal diagonal are ones and all other elements are zeros. The effect of multiplying a given matrix by an identity matrix is to leave the given matrix unchanged.

In [ ]:
array7=np.identity(10,dtype=int)
array7

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

**4.np.arange**

In [ ]:
array8=np.arange(50,100).reshape(10,5)
array8

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [ ]:
array8=np.arange(6,14,2)
array8

array([ 6,  8, 10, 12])

**5. np.linspace**

In [ ]:
array9=np.linspace(0,100,5)
array9

array([  0.,  25.,  50.,  75., 100.])

**6.copy**

In [ ]:
array10=array9.copy()
array10

array([  0.,  25.,  50.,  75., 100.])