In [ ]:
import numpy as np

**The following are attributes of numpy,so when object calls it we dont need to put brackets().It is required when object calls the function.**

**1. shape**(The shape of an array is the number of elements in each dimension)

In [ ]:
array1=np.array([1,2,3,4],dtype=int)
array1

array([1, 2, 3, 4])

In [ ]:
array1.shape

(4,)

In [ ]:
array2=np.array([[1,2],[3,4]])
array2

array([[1, 2],
       [3, 4]])

In [ ]:
array2.shape

(2, 2)

In [ ]:
array3=np.array([[[[[[1,2,3],[1,2,3],[1,2,3],[3,4,5,],[11,22,33]]]]]],dtype=float)
array3

array([[[[[[ 1.,  2.,  3.],
           [ 1.,  2.,  3.],
           [ 1.,  2.,  3.],
           [ 3.,  4.,  5.],
           [11., 22., 33.]]]]]])

In [ ]:
array3.shape

(1, 1, 1, 1, 5, 3)

**2. ndim**

In [ ]:
array1.ndim

1

In [ ]:
array2.ndim

2

In [ ]:
array3.ndim

6

**3.size**( count items from a given array and give output in the form of a number as size)

In [ ]:
array1.size

4

In [ ]:
array2.size

4

In [ ]:
array3.size

15

**4.	Item size** (returns the size (in bytes) of each element of a NumPy array)

In [ ]:
array1.itemsize

8

In [ ]:
array2.itemsize

8

In [ ]:
array3.itemsize

8

**5.	dtype**  (describes how the bytes in the xed-size block of memory corresponding to an array item should be interpreted. It describes the following aspects of the data: Type of the data (integer, float, Python object, etc.)

In [ ]:
array1.dtype

dtype('int64')

In [ ]:
array2.dtype

dtype('int64')

In [ ]:
array3.dtype

dtype('float64')

**6. astype** (It is a popular function in Python used to modify the dtype of the NumPy array we've been provided with. We'll use the numpy. astype() function to modify the dtype of the specied array object. The target data type, in this case, is crucial to be passed as an argument to the calling function)


In [ ]:
array2

array([[1, 2],
       [3, 4]])

In [ ]:
array2.astype("complex")

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [ ]:
array2 = array2.astype(str)
array2

array([['1', '2'],
       ['3', '4']], dtype='<U21')

In [ ]:
array2.dtype

dtype('<U21')