In [ ]:
import numpy as np

**Indexing and Slicing**

In [ ]:
array1=np.arange(30).reshape(5,6)
array1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
array1[2:4,1:3]
#first elaborate which rows are required and then which columns are required

array([[13, 14],
       [19, 20]])

In [ ]:
array1[0:2,4:6]

array([[ 4,  5],
       [10, 11]])

In [ ]:
array1[3:5]

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
array1[3]

array([18, 19, 20, 21, 22, 23])

In [ ]:
array1[:,2:4]

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21],
       [26, 27]])

In [ ]:
array1[0:2,3:5]

array([[ 3,  4],
       [ 9, 10]])

In [ ]:
array1[2:4,3:5]

array([[15, 16],
       [21, 22]])

In [ ]:
array2=np.arange(8)
array2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
array2[5]

5

In [ ]:
array2[4:8]

array([4, 5, 6, 7])

**iteration**

In [ ]:
for i in array1:
  print(i)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]


In [ ]:
for i in np.nditer(array1):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
