**1.	RAVEL (It converts the higher dimensional arrays to 1D arrays...similar to nditer)**

In [ ]:
import numpy as np
array1=np.array([1,2,3,4,5,6])
array2=np.array([6,7,8,9,10,11])
array3=array1.reshape(2,3)
array4=array2.reshape(2,3)

In [ ]:
array3

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array4

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
array4.ndim

2

In [ ]:
array3.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
array3

array([1, 2, 3, 4, 5, 6])

In [ ]:
array3.ndim

1

**2.reshape(already discussed in indexing)**

In [ ]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**3.transpose**

In [ ]:
array4

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
array4.transpose()

array([[ 6,  9],
       [ 7, 10],
       [ 8, 11]])

In [ ]:
array4

array([[ 6,  7,  8],
       [ 9, 10, 11]])

**4.stacking**

In [ ]:
np.hstack((array3,array4))

array([[ 1,  2,  3,  6,  7,  8],
       [ 4,  5,  6,  9, 10, 11]])

In [ ]:
np.vstack((array3,array4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

**5.splitting**

In [ ]:
array4

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.hsplit(array4,3)

[array([[6],
        [9]]),
 array([[ 7],
        [10]]),
 array([[ 8],
        [11]])]

In [ ]:
np.vsplit(array4,2)

[array([[6, 7, 8]]), array([[ 9, 10, 11]])]



---



---



# fancy indexing

**We can isolate different rows at different position**

In [ ]:
array1=np.arange(40).reshape(8,5)
array1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [ ]:
array1[[2,5,7]]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])