In [ ]:
import numpy as np

In [ ]:
array1=np.random.randint(1,100,20).reshape(4,5)
array1

array([[28, 49, 70, 57,  6],
       [50, 53, 75, 62, 19],
       [44, 77, 97, 32, 46],
       [60, 62, 92, 54, 72]])

**here we will do conditional indexing**

In [ ]:
array1[array1>30]

array([49, 70, 57, 50, 53, 75, 62, 44, 77, 97, 32, 46, 60, 62, 92, 54, 72])

In [ ]:
array1[(array1>30)&(array1 %2!=1)]

array([70, 50, 62, 44, 32, 46, 60, 62, 92, 54, 72])

In [ ]:
array1[(array1>30)&(array1 %2!=0)]=0
array1
#all values greater than 30 and odd becomes zero

array([ 0, 70,  0, 50,  0,  0, 62, 44,  0,  0, 32, 46, 60, 62, 92, 54, 72])